
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Simone
 */
public class CurrencyConverter extends javax.swing.JFrame {
    
    public static double balance = 0;
    /**
     * Creates new form CurrencyConverter
     */
    public CurrencyConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsPanel = new javax.swing.JPanel();
        depositBtn = new javax.swing.JButton();
        withdrawBtn = new javax.swing.JButton();
        historyBtn = new javax.swing.JButton();
        balanceBtn = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        tablePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        balancePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        balanceValue = new javax.swing.JLabel();
        depositPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        depositAmt = new javax.swing.JTextField();
        depositActionBtn = new javax.swing.JButton();
        currencyTypeList = new javax.swing.JComboBox<>();
        withdrawPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        withdrawAmt = new javax.swing.JTextField();
        withdrawActionBtn = new javax.swing.JButton();
        withdrawAllActionBtn = new javax.swing.JButton();
        historyPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                formAncestorResized(evt);
            }
        });

        buttonsPanel.setBackground(new java.awt.Color(72, 177, 204));

        depositBtn.setBackground(new java.awt.Color(215, 135, 74));
        depositBtn.setText("Deposit");
        depositBtn.setPreferredSize(new java.awt.Dimension(102, 29));
        depositBtn.setSize(new java.awt.Dimension(102, 29));
        depositBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositBtnActionPerformed(evt);
            }
        });

        withdrawBtn.setBackground(new java.awt.Color(215, 135, 74));
        withdrawBtn.setText("Withdraw");
        withdrawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawBtnActionPerformed(evt);
            }
        });

        historyBtn.setBackground(new java.awt.Color(215, 135, 74));
        historyBtn.setText("History");
        historyBtn.setMaximumSize(new java.awt.Dimension(102, 29));
        historyBtn.setMinimumSize(new java.awt.Dimension(102, 29));
        historyBtn.setPreferredSize(new java.awt.Dimension(102, 29));
        historyBtn.setSize(new java.awt.Dimension(102, 29));
        historyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyBtnActionPerformed(evt);
            }
        });

        balanceBtn.setBackground(new java.awt.Color(215, 135, 74));
        balanceBtn.setText("Balance");
        balanceBtn.setPreferredSize(new java.awt.Dimension(102, 29));
        balanceBtn.setSize(new java.awt.Dimension(102, 29));
        balanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(withdrawBtn)
                    .addComponent(historyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(balanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(depositBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(withdrawBtn)
                .addGap(44, 44, 44)
                .addComponent(historyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(244, 152, 81));
        mainPanel.setLayout(new java.awt.CardLayout());

        tablePanel.setBackground(new java.awt.Color(244, 152, 81));

        jLabel1.setFont(new java.awt.Font("Meiryo", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Converter");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 325, Short.MAX_VALUE))
        );

        mainPanel.add(tablePanel, "card3");

        balancePanel.setBackground(new java.awt.Color(244, 152, 81));

        jLabel2.setFont(new java.awt.Font("Meiryo", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Balance");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        balanceValue.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        balanceValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout balancePanelLayout = new javax.swing.GroupLayout(balancePanel);
        balancePanel.setLayout(balancePanelLayout);
        balancePanelLayout.setHorizontalGroup(
            balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balancePanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(balanceValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
        );
        balancePanelLayout.setVerticalGroup(
            balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balancePanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 325, Short.MAX_VALUE))
            .addGroup(balancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, balancePanelLayout.createSequentialGroup()
                    .addContainerGap(97, Short.MAX_VALUE)
                    .addComponent(balanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(119, Short.MAX_VALUE)))
        );

        mainPanel.add(balancePanel, "card3");

        depositPanel.setBackground(new java.awt.Color(244, 152, 81));

        jLabel3.setFont(new java.awt.Font("Meiryo", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Deposit");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        depositAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositAmtActionPerformed(evt);
            }
        });

        depositActionBtn.setText("Deposit");
        depositActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositActionBtnActionPerformed(evt);
            }
        });

        currencyTypeList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]
            { "U.S Dollars", "Euro", "British Pound", "Indian Rupee",
                "Austrailian Dollar", "Canadian Dollar", "Singapore Dollar", "Swiss Franc",
                "Malaysian Ringgit", "Japanese Yen", "Chinese Renminbi"}));
    currencyTypeList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    currencyTypeList.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            currencyTypeListMouseClicked(evt);
        }
    });
    currencyTypeList.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            currencyTypeListActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout depositPanelLayout = new javax.swing.GroupLayout(depositPanel);
    depositPanel.setLayout(depositPanelLayout);
    depositPanelLayout.setHorizontalGroup(
        depositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(depositPanelLayout.createSequentialGroup()
            .addGap(109, 109, 109)
            .addComponent(depositActionBtn)
            .addGap(0, 0, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositPanelLayout.createSequentialGroup()
            .addContainerGap(79, Short.MAX_VALUE)
            .addGroup(depositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(currencyTypeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(depositAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(71, 71, 71))
    );
    depositPanelLayout.setVerticalGroup(
        depositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(depositPanelLayout.createSequentialGroup()
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(25, 25, 25)
            .addComponent(depositAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(currencyTypeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
            .addComponent(depositActionBtn)
            .addGap(85, 85, 85))
    );

    mainPanel.add(depositPanel, "card3");

    withdrawPanel.setBackground(new java.awt.Color(244, 152, 81));

    jLabel4.setFont(new java.awt.Font("Meiryo", 1, 24)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel4.setText("Withdraw");
    jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
    jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    withdrawAmt.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            withdrawAmtActionPerformed(evt);
        }
    });

    withdrawActionBtn.setText("Withdraw");
    withdrawActionBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            withdrawActionBtnActionPerformed(evt);
        }
    });

    withdrawAllActionBtn.setText("Withdraw All");
    withdrawAllActionBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            withdrawAllActionBtnActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout withdrawPanelLayout = new javax.swing.GroupLayout(withdrawPanel);
    withdrawPanel.setLayout(withdrawPanelLayout);
    withdrawPanelLayout.setHorizontalGroup(
        withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(withdrawPanelLayout.createSequentialGroup()
            .addContainerGap(80, Short.MAX_VALUE)
            .addGroup(withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, withdrawPanelLayout.createSequentialGroup()
                    .addGroup(withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(withdrawAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(70, 70, 70))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, withdrawPanelLayout.createSequentialGroup()
                    .addComponent(withdrawActionBtn)
                    .addGap(104, 104, 104))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, withdrawPanelLayout.createSequentialGroup()
                    .addComponent(withdrawAllActionBtn)
                    .addGap(93, 93, 93))))
    );
    withdrawPanelLayout.setVerticalGroup(
        withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(withdrawPanelLayout.createSequentialGroup()
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(47, 47, 47)
            .addComponent(withdrawAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(withdrawActionBtn)
            .addGap(82, 82, 82)
            .addComponent(withdrawAllActionBtn)
            .addGap(0, 106, Short.MAX_VALUE))
    );

    mainPanel.add(withdrawPanel, "card3");

    historyPanel.setBackground(new java.awt.Color(244, 152, 81));

    jLabel5.setFont(new java.awt.Font("Meiryo", 1, 24)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("History");
    jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
    jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

    javax.swing.GroupLayout historyPanelLayout = new javax.swing.GroupLayout(historyPanel);
    historyPanel.setLayout(historyPanelLayout);
    historyPanelLayout.setHorizontalGroup(
        historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, historyPanelLayout.createSequentialGroup()
            .addContainerGap(79, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(74, 74, 74))
    );
    historyPanelLayout.setVerticalGroup(
        historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(historyPanelLayout.createSequentialGroup()
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 325, Short.MAX_VALUE))
    );

    mainPanel.add(historyPanel, "card3");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(buttonsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void historyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyBtnActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(historyPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_historyBtnActionPerformed

    private void balanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceBtnActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(balancePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        balanceValue.setText("$" + Double.toString(balance));
    }//GEN-LAST:event_balanceBtnActionPerformed

    private void depositBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositBtnActionPerformed
        // TODO add your handling code here:
        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(depositPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
        
    }//GEN-LAST:event_depositBtnActionPerformed

    private void withdrawBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawBtnActionPerformed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(withdrawPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_withdrawBtnActionPerformed

    private void formAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorResized
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorResized

    private void jLabel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1PropertyChange

    private void depositAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositAmtActionPerformed

    private void depositActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositActionBtnActionPerformed
        // TODO add your handling code here:
        if(depositAmt.getText() == null || Double.parseDouble(depositAmt.getText()) <= 0) {
            JOptionPane.showMessageDialog(null, 
                              "Invalid Entry!", 
                              "ERROR", 
                              JOptionPane.WARNING_MESSAGE);
        }
        else {
            String text = depositAmt.getText();
            double value = Double.parseDouble(text);
            String currencyType = currencyTypeList.getSelectedItem().toString();
            double convertedAmount = convertCurrency(value, currencyType);
            balance += convertedAmount;
        }
        depositAmt.setText(null);
    }//GEN-LAST:event_depositActionBtnActionPerformed

    private void withdrawAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawAmtActionPerformed

    private void withdrawActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawActionBtnActionPerformed
        // TODO add your handling code here:
        if(Double.parseDouble(withdrawAmt.getText()) > balance) {
            JOptionPane.showMessageDialog(null, 
                              "You do not have enough money to withdraw!", 
                              "ERROR", 
                              JOptionPane.WARNING_MESSAGE);
        }
        else {
            String text = withdrawAmt.getText();
            double value = Double.parseDouble(text);
            balance -= value;
        }
        withdrawAmt.setText(null);
    }//GEN-LAST:event_withdrawActionBtnActionPerformed

    private void withdrawAllActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawAllActionBtnActionPerformed
        // TODO add your handling code here:
        balance = 0;
    }//GEN-LAST:event_withdrawAllActionBtnActionPerformed

    private void currencyTypeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyTypeListActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_currencyTypeListActionPerformed

    private void currencyTypeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currencyTypeListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_currencyTypeListMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static double convertCurrency(double amount, String type) {
        double finalAmt = 0;
        
        switch(type) {
            case "U.S Dollars": {
                amount /= 1;
                break;
            }
            case "Euros": {
                amount /= 0.89;
                break;
            }
            case "British Pound": {
                amount /= 0.78;
                break;
            }
        }
        finalAmt = amount;
        return finalAmt;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
           new CurrencyConverter().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balanceBtn;
    private javax.swing.JPanel balancePanel;
    private javax.swing.JLabel balanceValue;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JComboBox<String> currencyTypeList;
    private javax.swing.JButton depositActionBtn;
    private javax.swing.JTextField depositAmt;
    private javax.swing.JButton depositBtn;
    private javax.swing.JPanel depositPanel;
    private javax.swing.JButton historyBtn;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JButton withdrawActionBtn;
    private javax.swing.JButton withdrawAllActionBtn;
    private javax.swing.JTextField withdrawAmt;
    private javax.swing.JButton withdrawBtn;
    private javax.swing.JPanel withdrawPanel;
    // End of variables declaration//GEN-END:variables
}
